### ISSUE TITLE
P4P+ maps default location Berlin, Germany

### ISSUE THREAD

**Issue by MohammedFayaj** [heremaps/here-android-sdk-examples#100]
I live in the US but whenever I switch on the here maps default map location is centered on Berlin, Germany. Can you help with that, please 
--

**Comment by Xgamefactory** [comment]
dont hope to try any feedback from here devs 
this github just opened for unknown user and adandoned. this default location hardcoded in sdk.
only solution is to get user location from location service and set map center by yourself.

**Comment by JH-YVR** [comment]
@MohammedFayaj , we have updated the example for map rendering to address your question. You will see an example of how to set the centre to any location (in the example it is set to Vancouver, Canada rather than using the default of Berlin). Also there is sample code in the developer guide under 'Basic Positioning' to show how to get the devices position and that can then be used to centre the map. Hope this helps!

**Comment by MohammedFayaj** [comment]
Thanks
