### ISSUE TITLE
Get unknown error while initializing map engine

### ISSUE THREAD

**Issue by nishantt12** [heremaps/here-android-sdk-examples#128]
@andrewcarter I am getting the same error tried both these solutions but not working.

1. Uninstall all of the apps you currently have installed which use the HERE SDK. Delete the shared map disk cache folder. It is located at getExternalStorageDirectory()/.here-maps, so for most devices the adb command to delete is: adb shell rm -r /sdcard/.here-maps

2. In your app specify an isolated disk cache location and MapService component as described here: Using an Isolated Map Disk Cache with the Map Service

here is the logcat:

06-07 15:21:52.138 23216 23216 E milezero_response: Map initialization error UNKNOWN details: Native engine initialization failed for unknown reason. stacktrace: java.lang.Throwable
06-07 15:21:52.138 23216 23216 E milezero_response: at com.nokia.maps.aw.a(EngineError.java:27)
06-07 15:21:52.138 23216 23216 E milezero_response: at com.nokia.maps.MapsEngine$h.a(MapsEngine.java:857)
06-07 15:21:52.138 23216 23216 E milezero_response: at com.nokia.maps.MapsEngine$h.a(MapsEngine.java:733)
06-07 15:21:52.138 23216 23216 E milezero_response: at com.nokia.maps.MapsEngine$h.doInBackground(MapsEngine.java:717)
06-07 15:21:52.138 23216 23216 E milezero_response: at android.os.AsyncTask$2.call(AsyncTask.java:304)
06-07 15:21:52.138 23216 23216 E milezero_response: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-07 15:21:52.138 23216 23216 E milezero_response: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
06-07 15:21:52.138 23216 23216 E milezero_response: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-07 15:21:52.138 23216 23216 E milezero_response: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-07 15:21:52.138 23216 23216 E milezero_response: at java.lang.Thread.run(Thread.java:761)
06-07 15:21:52.176 23216 23521 W cr_CrashFileManager:

**Comment by starand** [comment]
Hi @nishantt12,
That error can be returned in case **MapService** is being started from background. This is known Android restriction (starting from Android O) - https://developer.android.com/about/versions/oreo/android-8.0-changes#back-all

On the other hand, SDK can return **UNKNOWN** error in other cases. The following callback - onEngineInitializationCompleted(Error error), provides information about error and Error type is an enum. But this enum also has **getDetails()** and **getStackTrace()** method. Could you please provide such info to understand a root cause?
Please try to use recently released SDK 3.9 where we improved error reporting.
