### ISSUE TITLE
Not able to add Image Direction icon

### ISSUE THREAD

**Issue by arorayogita** [heremaps/here-android-sdk-examples#150]
I am not able to find the icon from here sdk as i m getting  enum types and values like :  QUITE_RIGHT(5)

**Comment by NazarKacharaba** [comment]
What API do you use, what are you truing to active?
Please make question a bit more clear, maybe show code snippets.

**Comment by arorayogita** [comment]
I am working on Truck Navigation,So I want to display Icons on my Notification.
I have implemented ManeuverEventListener and NewInstructionEventListener to get details of Route


 Maneuver m = NavigationManager.getInstance().getNextManeuver();
            Log.i("tag", "New instruction : in " + NavigationManager.getInstance().getNextManeuverDistance() + " m do " + m.getTurn().name() + " / " + m.getAction().name() + " on " + m.getNextRoadName() + " (from " + m.getRoadName() + ")" + "image" + m.getNextRoadImage() + "icon" + m.getIcon().value());

I am not able to get Image from m.getNextRoadImage()  and m.getIcon() this code just returns enums like  QUITE_RIGHT(5), TURN_LEFT, So I need to show Images.

**Comment by NazarKacharaba** [comment]
`Maneuver.getNextRoadImage()` returns the `Image` object of the road this maneuver leads to. In some cases it can be null, that is expected behaviour.
`Maneuver.getIcon()` returns enum value that you can map to your own bitmaps. SDK does not provide those bitmaps for you.

In your case you should rely on `Maneuver.getIcon()` as it is always [NonNull](https://developer.android.com/reference/android/support/annotation/NonNull). Create your own graphic images and use them.

**Comment by arorayogita** [comment]
Thanks for the Info.
