### ISSUE TITLE
Cant resolve HERE-sdk dependency

### ISSUE THREAD

**Issue by mayuroks** [heremaps/here-android-sdk-examples#16]
I clone the demo app and tried running it using Android studio.
But I am unable to install it, since this dependency is not met.

```
compile(name: 'HERE-sdk', ext: 'aar')
```

**Can anyone help ?**

**Comment by sschuberth** [comment]
Hi @mayuroks, thanks for giving the Android SDk examples a try. Please have a look at the [README](https://github.com/heremaps/here-android-sdk-examples/blob/master/README.md) which provides instructions on how to sign up for a free trial of the Premium SDK in order to get access to this required dependency.

On https://developer.here.com/, once you've entered the package name of the desired example to build, the App ID, App Code and License Key get generated and you can download Premium Android SDK. Enter the App ID, App Code and License Key into the example's `AndroidManifest.xml`, and extract `HERE-sdk.aar` from the nested `HERE-sdk.zip\HERE-sdk\libs` directory to put it into the example's `app\libs` directory.

That should get you going, but I see now how we could improve the README with some screenshots. I'll try to do that soonish.

Let me know it this works for you!

**Comment by mayuroks** [comment]
Thanks for responsing quickly.
But after this I am getting a different error
```
import com.here.android.mpa.search.AroundRequest;
```
**I am unable to import this request.**

Just FYI this is search-android codebase I am trying to build and run.

**Comment by sschuberth** [comment]
Thanks for the report, I'll look into it.

**Comment by sschuberth** [comment]
I'm sorry, but I'm unable to reproduce the issue. I just checked, and for me the `com.here.android.example.search` example builds and runs fine. Are you sure you've copied the correct `HERE-sdk.aar` (it should be sized about 19.8 MiB) into the `search-android\app\libs` directory?

**Comment by sschuberth** [comment]
Any update @mayuroks?
