### ISSUE TITLE
Please let me know how to overcome this

### ISSUE THREAD

**Issue by askarali** [heremaps/here-android-sdk-examples#199]
Please let me know how to over come this

_Originally posted by @askarali in https://github.com/heremaps/here-android-sdk-examples/issue_comments#issuecomment-449947424_

**Comment by starand** [comment]
Hi @askarali 
Which sample app has the issue?
If you want to avoid **UnintializedMapEngineException**, you have to wait for completion of MapEngine initialization - for onEngineInitializationCompleted() callback.

```
        ApplicationContext context = new ApplicationContext(getApplicationContext());
        MapEngine.getInstance().init(context, new OnEngineInitListener() {
            @Override
            public void onEngineInitializationCompleted(Error error) {
                if (error == Error.NONE) {
                   // you are ready to create SDK objects
                   ...
                }
            }
        });
```

**Comment by askarali** [comment]
I have used turn by turn navigation which is some time work fine without any issues. when I find the issue I will clear the app from recent and open it again then it will start working

**Comment by starand** [comment]
Does it mean you cannot reproduce it for now? And whether we can solve the ticket?

**Comment by askarali** [comment]
it is not happening always.so i cant reproduce this issue

**Comment by EugeneZaychenko** [comment]
I continue to receive the same error in a different situation. Сan I create a GeoCoordinate object if the map is not yet initialized?

**Comment by NazarKacharaba** [comment]
Lots of classes in the SDK require that native libs are already loaded(internally via `System. loadLibrary(...)`) so that is why you always need to call `MapEngine.init(...)` at the beginning of the SDK usage. Class `GeoCoordinate` is one of them.

Try always check if `MapEngine.isInitialized()` in the places that you're not sure `MapEngine` is initialized, e.g. in `Service` when push notification is received, in `BroadcastReceiver` when some system event is triggered etc.

**Comment by starand** [comment]
@askarali was your issue solved?
