### ISSUE TITLE
traffic layer not visible

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-android-sdk-examples#221]
we are trying to make traffic lines visible on map
tried this traffic ralated codes on map initialized. nothing shown.

```
map.setMapScheme(Map.Scheme.NORMAL_TRAFFIC_DAY);
map.setTrafficInfoVisible(true);        map.getMapTrafficLayer().setEnabled(MapTrafficLayer.RenderLayer.FLOW,true);
```

**Comment by starand** [comment]
Hi @Xgamefactory,

Which location do you use to get traffic data?
Meanwhile, you can try that option:
Request traffic manually (see request() methods in TrafficUpdater documentation), e.g.:
                TrafficUpdater.getInstance().request(m_map.getCenter(), new TrafficUpdater.Listener() {
                    @Override
                    public void onStatusChanged(TrafficUpdater.RequestState state) {
                        Toast.makeText(getActivity(),
                                "Traffic GeoCoordinate RequestState: " + state.toString(),
                                Toast.LENGTH_SHORT).show();
                    }
                });

**Comment by Xgamefactory** [comment]
we are testing currently in baku Azerbaijan on previous version there was traffic layer visible in baku.
we just need map traffic layer not traffic informations.

**Comment by starand** [comment]
Not familiar with your code but due to documentation:
1) MapTrafficLayer.setEnabled() - 
> Enable a Traffic Layer defined in {@code RenderLayer}. The default behavior is that all {@link RenderLayer RenderLayers} are enabled.
Therefore you have to disable what you do not need, e.g.:
`map.getMapTrafficLayer().setEnabled(MapTrafficLayer.RenderLayer.INCIDENT,false);`
2) MapTrafficLayer class is not responsible for requesting traffic from server, just rendering:
> Class to represent Traffic rendering information. This class can be used to control which typesof traffic are rendered.
3) If there is no traffic info, how the map can display it? Therefore you have to request it using TrafficUpdater.
> Controls traffic update requests.

Regarding traffic in Baku I will clarify and will respond later. At least I can see it in Berlin.

**Comment by starand** [comment]
Unfortunately we do not support traffic in Azerbaijan.
