### ISSUE TITLE
new route after reroute is not ideal

### ISSUE THREAD

**Issue by bluesnow4425** [heremaps/here-android-sdk-examples#296]
Hi,
Recently we're trying Here sdk reroute, and we're not really satisfied with new routes. In this case (please refer to attachment), the navigation suggests driver to make u-turn and leave the highway at original exit, which is quite unnatural. We expect rerouting leads driver to the next exit and find other road to the destination, which is faster and more natural. We tested android and ios navigation simultaneously, and this happens on both platforms. 
https://drive.google.com/file/d/1-13r9U2aAxRhHZFeKQXzPZfl1JYeDxxI/view

**Comment by starand** [comment]
Hi @bluesnow4425,
Assumption "We expect rerouting leads driver to the next exit and find other road to the destination, which is faster and more natural" is not correct. It may feel more natural, but may well not be faster - and finding a faster route is the most important thing for the routing engine.
You have to provide all details (like waypoints, traffic mode and so on) so that we can try to reproduce the issue.

**Comment by starand** [comment]
Closing ticket as no details provided. Please reopen if needed.
