### ISSUE TITLE
How to get transit routes same as Here WeGo app?

### ISSUE THREAD

**Issue by ChenYuehNung** [heremaps/here-android-sdk-examples#309]
Hi ~
We are using the Premium SDK (v3.13.3) to implement transit routing. But we don't know why the SDK results are so different from the Here WeGo app every time. In the Here WeGo app, you can get more results with the same O / D and departure time. Why? It  is not the same core resource?! Or can you tell me how to get the transit routes same as the HERE WeGo app?

**Comment by starand** [comment]
Hi @ChenYuehNung, thanks for the question. We will take a look and respond.

**Comment by haffax** [comment]
Hello @ChenYuehNung 

Not all sources for transit routes are available through the SDK for 3rd party out of the box as they may require agreeing to additional terms or due to other reasons.

You can learn more about public transit coverage and how to request further support on this page: https://developer.here.com/documentation/transit/dev_guide/topics/coverage-information.html
