### ISSUE TITLE
Why don't maps of China, Japan and South Korea show detailed streets and so on?

### ISSUE THREAD

**Issue by LiXiaohezi** [heremaps/here-android-sdk-examples#324]
Why don't maps of China, Japan and South Korea show detailed streets and so on? How to solve this situation?

**Comment by tlushney** [comment]
These regions have restrictions for distribution geographic data out of country and HERE SDK respects these restrictions.
HERE SDK supports detailed map for South Korea and China, and for these maps HERE SDK provides special map variants.

For now HERE SDK supports there variants:
- GLOBAL -  world map.
- CHINA - world map including China detailed map.
- KOREA - world map including Korean detailed map.

See more details:
https://developer.here.com/documentation/android-premium/api_reference_java/com/here/android/mpa/common/MapEngine.MapVariant.html

Korean or China maps are not included standard licence. And in order to use either Korean or China, you should consult with HERE representative.

For now, Japan map is not supported by HERE SDK.
