### ISSUE TITLE
QUESTION: Data usage optimization

### ISSUE THREAD

**Issue by ne2rnas** [heremaps/here-android-sdk-examples#427]
Hello! I'm using Android Premium SDK. 

I've got complaints from users that our app uses too much mobile data.

I wonder what could be done to optimize mobile data usage on Here SDK's end.

Can you answer some of my questions?

1. There's a method called ```ApplicationContext.setDiskCacheSize()```
Right now app uses the default value of **256 MB**. I figured increasing cache size could potentially prevent SDK from downloading additional data. After reading the documentation I've found out that the maximum cache size is **2048 MB**. Does increasing the cache size going to reduce the mobile data usage?

2. Is it possible to minimize HERE SDK's downloads size by playing around with schemes? The map scheme is being set by ```map.setMapScheme()```... I've found this scheme called ```Map.Scheme.MANEUVER_DAY```. After running the app I've noticed that a lot of stuff isn't being render. Only the most critical components like roads, route and some geograpical objects are being rendered. So my questions is this: does HERE SDK download data for not rendered Map objects?
 Nevertheless, I cannot use ```Map.Scheme.MANEUVER_DAY``` because I have implemented traffic visibility with ```Map.setTrafficInfoVisible(true)```. But maybe I could reduce the amount of objects being rendered by creating a custom scheme?

3. Does disabling extruded buildings visibility reduces the mobile data usage? E.g.: ```map.setExtrudedBuildingsVisible(false)```.

4. Our app is being preloaded to devices which are then given to users. Would it be wise to download offline maps and sideload offline maps to every device given to users? I've tested this approach and it kinda works when transfering offline maps to ```setIsolatedDiskCacheRootPath``` directory. But I'm nervous about offline maps updates which could potentially use a lot of data and moreover this approach seems hacky.

Maybe you have any tips and tricks on how could I reduce the amount of mobile data being used?

Thanks.

**Comment by NazarKacharaba** [comment]
Hi @ne2rnas 

> Does increasing the cache size going to reduce the mobile data usage?

Yes. Small cache size will result in more frequent cache purging in order to make space available for new map data. Large cache size will increase the likelihood that previously downloaded map data will be available in the cache when needed.

 > But maybe I could reduce the amount of objects being rendered by creating a custom scheme?

You can reduce map data size by using MapLoader.selectDataGroup(...). However it only works if use load map data using _MapLoader_ API.

>Does disabling extruded buildings visibility reduces the mobile data usage.

No. This is only `UI rendering` option, does not make any difference in data downloading.  

>Would it be wise to download offline maps and sideload offline maps to every device given to users? But I'm nervous about offline maps updates which could potentially use a lot of data and moreover this approach seems hacky.

Yes. It is good option. If you perform map data updates very rarely, then yes, there is high chance that new map update will cause whole data to be re-downloaded. But if updates happens regularly, it will be `incremental updates` that are typically small downloads as only the changes are downloaded. [See dev guide section](https://developer.here.com/documentation/android-premium/3.17/dev_guide/topics/maps-offline-maploader.html).
