### ISSUE TITLE
navigation issue

### ISSUE THREAD

**Issue by alexsafe** [heremaps/here-android-sdk-examples#46]
[
![app](https://cloud.githubusercontent.com/assets/5214149/26742463/be19eb74-47ab-11e7-8bed-734734d43fa1.png)
![heremaps](https://cloud.githubusercontent.com/assets/5214149/26742468/c378e39a-47ab-11e7-944a-16bd0645a73a.PNG)
![gmaps](https://cloud.githubusercontent.com/assets/5214149/26742471/c6769db2-47ab-11e7-8331-16b9ccb47513.png)

](url)

Hi,

I have encountered an issue with the Android SDK routePlan. The route suggested by our app differs form the one sugested by the Here App, here maps web app, and google maps.  I am not sure what the issue is, but maybe you can offer some support on this. There is a an error of a few meters on the coordinates in the app, but the HERE web app is reverse geocoding the coordinates so maybe that's why it works correctly. I have included the screenshots.

Thanks,
Alex

**Comment by paramtrivedi** [comment]
@sschuberth Any comments here?

**Comment by JH-YVR** [comment]
@paramtrivedi  and @alexsafe, recommend you post such questions to https://stackoverflow.com/questions/tagged/here-api as they will likely get a response faster. This site should be used to ask questions or raise issues regarding the examples.

I suspect the difference you are seeing in the routes is due to differences in the coordinates for the destination. I quickly checked wego.here.com and the route returned is the same as in your application when using the street address.  Feel free to follow up at: https://stackoverflow.com/questions/tagged/here-api
