### ISSUE TITLE
Routing errors due to connectivity loss are hard to trace

### ISSUE THREAD

**Issue by jbxbergdev** [heremaps/here-android-sdk-examples#79]
Regarding routing errors, the CoreRouter.Listener and NavigationManager.RerouteListener interfaces aren't consistent with each other: On initial route calculation, Listener.onCalculateRouteFinished() will receive RouteResults as well as RoutingErrors. So I can tell, for example, if route calculation failed due to network loss (GRAPH_DISCONNECTED).

There is however no such mechanism in NavigationManager.RerouteListener: onRerouteFailed() gives no reason _why_ route recalculation failed.Also, onRerouteEnd() will be called with the old RouteResult (or so it seems) if connectivity was lost, instead of onRerouteFailed(). 

IMO it would be best if the SDK would provide a callback that communicates connection loss with HERE servers.

**Comment by AmbroseLi** [comment]
Hi @jbxbergdev.  Thanks for the feedback.  The SDK dev. team will review this.

On an aside, we have an active community in Stack Overflow (tag: [here-api]) where our team and others in the community hang out. Should you have questions you'd like to raise about the SDK or have improvements/suggestion, please feel free to post them there.

**Comment by Xgamefactory** [comment]
this should be fixed.
also your in stackoverflow most important questions has not been asnwered 
you can weakest support among other companies which provides navigation sdk.
Lack of advanced examples is a minus too.
instead of forwarding developers to stackoverflow you should handle it on your github.
that would be more professional in our opinion. 
You provide premium sdk not and opensource stuff so please make your support really premimum.

**Comment by starand** [comment]
This will be fixed in SDK 3.10 (estimated release date 17th of Dec).
