### ISSUE TITLE
need some examples for animating position marker

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-android-sdk-examples#84]
currently during rerouting marker just flies through the building
there should be some fast snapping options
also animating on turns like google drives does.

**Comment by nsurgeon** [comment]
Please provide more detailed information what exactly you see and what is wrong.
I tried simulation with reroutings (with tilted map where I see 3d buildings) and everything looks fine to me.

If you could attach video or screenshot with issue it will be great

**Comment by parmarravi** [comment]
Hi @Xgamefactory, For turns you will require to rotate the markers as you approach the geoCordinate . you can do animations on marker by passing multiple points in animation method of android . Use handler as much as possible for clean animations.  Even in google the  marker flies from one point to second . I think this happens because your animation method is trying to reach the end point as soon as the time is reaching to completion .If u can make a set of points between A and B  u can achieve better results with proper animation timing.
